# coding: utf-8

"""
    Appwrite

    Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

    The version of the OpenAPI document: 1.5.0
    Contact: team@appwrite.io
    Created by: https://appwrite.io/support
"""

from appwrite_console_python_sdk.paths.functions_function_id_deployments.post import CreateDeploymentRaw
from appwrite_console_python_sdk.paths.functions.post import CreateFunctionRaw
from appwrite_console_python_sdk.paths.functions_function_id_variables.post import CreateVariableRaw
from appwrite_console_python_sdk.paths.functions_function_id_deployments_deployment_id.delete import DeleteDeploymentRaw
from appwrite_console_python_sdk.paths.functions_function_id.delete import DeleteFunctionByIdRaw
from appwrite_console_python_sdk.paths.functions_function_id_variables_variable_id.delete import DeleteVariableByIdRaw
from appwrite_console_python_sdk.paths.functions_function_id_deployments_deployment_id_download.get import DownloadDeploymentContentsRaw
from appwrite_console_python_sdk.paths.functions_function_id.get import GetByIdRaw
from appwrite_console_python_sdk.paths.functions_function_id_deployments_deployment_id.get import GetDeploymentByIdRaw
from appwrite_console_python_sdk.paths.functions_function_id_executions_execution_id.get import GetExecutionLogRaw
from appwrite_console_python_sdk.paths.functions_function_id_usage.get import GetFunctionUsageRaw
from appwrite_console_python_sdk.paths.functions_usage.get import GetUsageStatsRaw
from appwrite_console_python_sdk.paths.functions_function_id_variables_variable_id.get import GetVariableByIdRaw
from appwrite_console_python_sdk.paths.functions.get import ListAllRaw
from appwrite_console_python_sdk.paths.functions_function_id_deployments.get import ListDeploymentsRaw
from appwrite_console_python_sdk.paths.functions_function_id_executions.get import ListExecutionsRaw
from appwrite_console_python_sdk.paths.functions_runtimes.get import ListRuntimesRaw
from appwrite_console_python_sdk.paths.functions_function_id_variables.get import ListVariablesRaw
from appwrite_console_python_sdk.paths.functions_function_id_deployments_deployment_id_builds_build_id.post import RetryBuildRaw
from appwrite_console_python_sdk.paths.functions_function_id_executions.post import TriggerExecutionRaw
from appwrite_console_python_sdk.paths.functions_function_id.put import UpdateByIdRaw
from appwrite_console_python_sdk.paths.functions_function_id_deployments_deployment_id.patch import UpdateDeploymentByFunctionAndIdRaw
from appwrite_console_python_sdk.paths.functions_function_id_variables_variable_id.put import UpdateVariableByIdRaw


class FunctionsApiRaw(
    CreateDeploymentRaw,
    CreateFunctionRaw,
    CreateVariableRaw,
    DeleteDeploymentRaw,
    DeleteFunctionByIdRaw,
    DeleteVariableByIdRaw,
    DownloadDeploymentContentsRaw,
    GetByIdRaw,
    GetDeploymentByIdRaw,
    GetExecutionLogRaw,
    GetFunctionUsageRaw,
    GetUsageStatsRaw,
    GetVariableByIdRaw,
    ListAllRaw,
    ListDeploymentsRaw,
    ListExecutionsRaw,
    ListRuntimesRaw,
    ListVariablesRaw,
    RetryBuildRaw,
    TriggerExecutionRaw,
    UpdateByIdRaw,
    UpdateDeploymentByFunctionAndIdRaw,
    UpdateVariableByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
