# coding: utf-8

"""
    Appwrite

    Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

    The version of the OpenAPI document: 1.5.0
    Contact: team@appwrite.io
    Created by: https://appwrite.io/support
"""

from appwrite_console_python_sdk.paths.health_queue_certificates.get import CertificatesQueueCount
from appwrite_console_python_sdk.paths.health.get import CheckAppwriteHttpServer
from appwrite_console_python_sdk.paths.health_anti_virus.get import CheckAvStatus
from appwrite_console_python_sdk.paths.health_cache.get import CheckCacheStatus
from appwrite_console_python_sdk.paths.health_db.get import CheckDatabaseStatus
from appwrite_console_python_sdk.paths.health_storage_local.get import CheckLocalStorage
from appwrite_console_python_sdk.paths.health_queue.get import CheckQueueStatus
from appwrite_console_python_sdk.paths.health_storage.get import CheckStorageDevice
from appwrite_console_python_sdk.paths.health_queue_functions.get import FunctionsQueueCount
from appwrite_console_python_sdk.paths.health_queue_builds.get import GetBuildsQueue
from appwrite_console_python_sdk.paths.health_queue_databases.get import GetDatabasesQueue
from appwrite_console_python_sdk.paths.health_queue_failed_name.get import GetFailedJobs
from appwrite_console_python_sdk.paths.health_queue_mails.get import GetMailsQueue
from appwrite_console_python_sdk.paths.health_queue_messaging.get import GetMessagingQueue
from appwrite_console_python_sdk.paths.health_queue_migrations.get import GetMigrationsQueue
from appwrite_console_python_sdk.paths.health_queue_deletes.get import GetQueueDeletes
from appwrite_console_python_sdk.paths.health_queue_logs.get import GetQueueLogs
from appwrite_console_python_sdk.paths.health_queue_usage.get import GetQueueUsageMetrics
from appwrite_console_python_sdk.paths.health_certificate.get import GetSslCertificate
from appwrite_console_python_sdk.paths.health_queue_usage_dump.get import GetUsageDumpQueue
from appwrite_console_python_sdk.paths.health_pubsub.get import PubsubGet
from appwrite_console_python_sdk.paths.health_time.get import SyncTimeWithNtp
from appwrite_console_python_sdk.paths.health_queue_webhooks.get import WebhooksQueueCount
from appwrite_console_python_sdk.apis.tags.health_api_raw import HealthApiRaw


class HealthApi(
    CertificatesQueueCount,
    CheckAppwriteHttpServer,
    CheckAvStatus,
    CheckCacheStatus,
    CheckDatabaseStatus,
    CheckLocalStorage,
    CheckQueueStatus,
    CheckStorageDevice,
    FunctionsQueueCount,
    GetBuildsQueue,
    GetDatabasesQueue,
    GetFailedJobs,
    GetMailsQueue,
    GetMessagingQueue,
    GetMigrationsQueue,
    GetQueueDeletes,
    GetQueueLogs,
    GetQueueUsageMetrics,
    GetSslCertificate,
    GetUsageDumpQueue,
    PubsubGet,
    SyncTimeWithNtp,
    WebhooksQueueCount,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: HealthApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = HealthApiRaw(api_client)
