# coding: utf-8

"""
    Appwrite

    Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

    The version of the OpenAPI document: 1.5.0
    Contact: team@appwrite.io
    Created by: https://appwrite.io/support
"""

from appwrite_console_python_sdk.paths.health_queue_certificates.get import CertificatesQueueCountRaw
from appwrite_console_python_sdk.paths.health.get import CheckAppwriteHttpServerRaw
from appwrite_console_python_sdk.paths.health_anti_virus.get import CheckAvStatusRaw
from appwrite_console_python_sdk.paths.health_cache.get import CheckCacheStatusRaw
from appwrite_console_python_sdk.paths.health_db.get import CheckDatabaseStatusRaw
from appwrite_console_python_sdk.paths.health_storage_local.get import CheckLocalStorageRaw
from appwrite_console_python_sdk.paths.health_queue.get import CheckQueueStatusRaw
from appwrite_console_python_sdk.paths.health_storage.get import CheckStorageDeviceRaw
from appwrite_console_python_sdk.paths.health_queue_functions.get import FunctionsQueueCountRaw
from appwrite_console_python_sdk.paths.health_queue_builds.get import GetBuildsQueueRaw
from appwrite_console_python_sdk.paths.health_queue_databases.get import GetDatabasesQueueRaw
from appwrite_console_python_sdk.paths.health_queue_failed_name.get import GetFailedJobsRaw
from appwrite_console_python_sdk.paths.health_queue_mails.get import GetMailsQueueRaw
from appwrite_console_python_sdk.paths.health_queue_messaging.get import GetMessagingQueueRaw
from appwrite_console_python_sdk.paths.health_queue_migrations.get import GetMigrationsQueueRaw
from appwrite_console_python_sdk.paths.health_queue_deletes.get import GetQueueDeletesRaw
from appwrite_console_python_sdk.paths.health_queue_logs.get import GetQueueLogsRaw
from appwrite_console_python_sdk.paths.health_queue_usage.get import GetQueueUsageMetricsRaw
from appwrite_console_python_sdk.paths.health_certificate.get import GetSslCertificateRaw
from appwrite_console_python_sdk.paths.health_queue_usage_dump.get import GetUsageDumpQueueRaw
from appwrite_console_python_sdk.paths.health_pubsub.get import PubsubGetRaw
from appwrite_console_python_sdk.paths.health_time.get import SyncTimeWithNtpRaw
from appwrite_console_python_sdk.paths.health_queue_webhooks.get import WebhooksQueueCountRaw


class HealthApiRaw(
    CertificatesQueueCountRaw,
    CheckAppwriteHttpServerRaw,
    CheckAvStatusRaw,
    CheckCacheStatusRaw,
    CheckDatabaseStatusRaw,
    CheckLocalStorageRaw,
    CheckQueueStatusRaw,
    CheckStorageDeviceRaw,
    FunctionsQueueCountRaw,
    GetBuildsQueueRaw,
    GetDatabasesQueueRaw,
    GetFailedJobsRaw,
    GetMailsQueueRaw,
    GetMessagingQueueRaw,
    GetMigrationsQueueRaw,
    GetQueueDeletesRaw,
    GetQueueLogsRaw,
    GetQueueUsageMetricsRaw,
    GetSslCertificateRaw,
    GetUsageDumpQueueRaw,
    PubsubGetRaw,
    SyncTimeWithNtpRaw,
    WebhooksQueueCountRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
