# coding: utf-8

"""
    Appwrite

    Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

    The version of the OpenAPI document: 1.5.0
    Contact: team@appwrite.io
    Created by: https://appwrite.io/support
"""

from appwrite_console_python_sdk.paths.migrations_appwrite.post import CreateAppwriteMigrationRaw
from appwrite_console_python_sdk.paths.migrations_nhost.post import CreateNHostMigrationRaw
from appwrite_console_python_sdk.paths.migrations_migration_id.delete import DeleteMigrationRaw
from appwrite_console_python_sdk.paths.migrations_firebase.post import FirebaseDataMigrationRaw
from appwrite_console_python_sdk.paths.migrations_firebase_oauth.post import FirebaseOAuthMigrateRaw
from appwrite_console_python_sdk.paths.migrations_firebase_report.get import GenerateFirebaseReportRaw
from appwrite_console_python_sdk.paths.migrations_firebase_report_oauth.get import GenerateFirebaseReportOAuthRaw
from appwrite_console_python_sdk.paths.migrations_nhost_report.get import GenerateNhostReportRaw
from appwrite_console_python_sdk.paths.migrations_appwrite_report.get import GenerateReportOnAppwriteDataRaw
from appwrite_console_python_sdk.paths.migrations_supabase_report.get import GenerateSupabaseReportRaw
from appwrite_console_python_sdk.paths.migrations_migration_id.get import GetByIdRaw
from appwrite_console_python_sdk.paths.migrations_firebase_projects.get import ListFirebaseProjectsRaw
from appwrite_console_python_sdk.paths.migrations.get import ListMigrationsRaw
from appwrite_console_python_sdk.paths.migrations_supabase.post import MigrateSupabaseDataRaw
from appwrite_console_python_sdk.paths.migrations_migration_id.patch import RetryMigrationRaw
from appwrite_console_python_sdk.paths.migrations_firebase_deauthorize.get import RevokeFirebaseAuthorizationRaw


class MigrationsApiRaw(
    CreateAppwriteMigrationRaw,
    CreateNHostMigrationRaw,
    DeleteMigrationRaw,
    FirebaseDataMigrationRaw,
    FirebaseOAuthMigrateRaw,
    GenerateFirebaseReportRaw,
    GenerateFirebaseReportOAuthRaw,
    GenerateNhostReportRaw,
    GenerateReportOnAppwriteDataRaw,
    GenerateSupabaseReportRaw,
    GetByIdRaw,
    ListFirebaseProjectsRaw,
    ListMigrationsRaw,
    MigrateSupabaseDataRaw,
    RetryMigrationRaw,
    RevokeFirebaseAuthorizationRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
