# coding: utf-8

"""
    Appwrite

    Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

    The version of the OpenAPI document: 1.5.0
    Contact: team@appwrite.io
    Created by: https://appwrite.io/support
"""

from appwrite_console_python_sdk.paths.proxy_rules.post import CreateNewRule
from appwrite_console_python_sdk.paths.proxy_rules_rule_id.delete import DeleteRuleById
from appwrite_console_python_sdk.paths.proxy_rules_rule_id.get import GetRuleById
from appwrite_console_python_sdk.paths.proxy_rules.get import ListRules
from appwrite_console_python_sdk.paths.proxy_rules_rule_id_verification.patch import UpdateRuleVerificationStatus
from appwrite_console_python_sdk.apis.tags.proxy_api_raw import ProxyApiRaw


class ProxyApi(
    CreateNewRule,
    DeleteRuleById,
    GetRuleById,
    ListRules,
    UpdateRuleVerificationStatus,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ProxyApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ProxyApiRaw(api_client)
