# coding: utf-8

"""
    Appwrite

    Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

    The version of the OpenAPI document: 1.5.0
    Contact: team@appwrite.io
    Created by: https://appwrite.io/support
"""

from appwrite_console_python_sdk.paths.teams_team_id_memberships.post import CreateMembership
from appwrite_console_python_sdk.paths.teams.post import CreateTeam
from appwrite_console_python_sdk.paths.teams_team_id.get import GetById
from appwrite_console_python_sdk.paths.teams.get import GetFilteredTeams
from appwrite_console_python_sdk.paths.teams_team_id_memberships_membership_id.get import GetMembership
from appwrite_console_python_sdk.paths.teams_team_id_prefs.get import GetPrefs
from appwrite_console_python_sdk.paths.teams_team_id_logs.get import ListLogs
from appwrite_console_python_sdk.paths.teams_team_id_memberships.get import ListMemberships
from appwrite_console_python_sdk.paths.teams_team_id.delete import RemoveById
from appwrite_console_python_sdk.paths.teams_team_id_memberships_membership_id.delete import RemoveMembership
from appwrite_console_python_sdk.paths.teams_team_id_memberships_membership_id.patch import UpdateMembershipRoles
from appwrite_console_python_sdk.paths.teams_team_id_memberships_membership_id_status.patch import UpdateMembershipStatus
from appwrite_console_python_sdk.paths.teams_team_id.put import UpdateNameById
from appwrite_console_python_sdk.paths.teams_team_id_prefs.put import UpdatePrefsById
from appwrite_console_python_sdk.apis.tags.teams_api_raw import TeamsApiRaw


class TeamsApi(
    CreateMembership,
    CreateTeam,
    GetById,
    GetFilteredTeams,
    GetMembership,
    GetPrefs,
    ListLogs,
    ListMemberships,
    RemoveById,
    RemoveMembership,
    UpdateMembershipRoles,
    UpdateMembershipStatus,
    UpdateNameById,
    UpdatePrefsById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TeamsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TeamsApiRaw(api_client)
