# coding: utf-8

"""
    Appwrite

    Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

    The version of the OpenAPI document: 1.5.0
    Contact: team@appwrite.io
    Created by: https://appwrite.io/support
"""

from appwrite_console_python_sdk.paths.vcs_github_installations_installation_id_repositories_repository_id.patch import AuthorizeExternalDeployment
from appwrite_console_python_sdk.paths.vcs_github_installations_installation_id_provider_repositories.post import CreateProviderRepository
from appwrite_console_python_sdk.paths.vcs_installations_installation_id.delete import DeleteInstallation
from appwrite_console_python_sdk.paths.vcs_github_installations_installation_id_provider_repositories_provider_repository_id_detection.post import DetectRuntimeSettings
from appwrite_console_python_sdk.paths.vcs_installations_installation_id.get import GetInstallationById
from appwrite_console_python_sdk.paths.vcs_github_installations_installation_id_provider_repositories_provider_repository_id.get import GetRepository
from appwrite_console_python_sdk.paths.vcs_installations.get import ListInstallations
from appwrite_console_python_sdk.paths.vcs_github_installations_installation_id_provider_repositories.get import ListProviderRepositories
from appwrite_console_python_sdk.paths.vcs_github_installations_installation_id_provider_repositories_provider_repository_id_branches.get import ListRepositoryBranches
from appwrite_console_python_sdk.apis.tags.vcs_api_raw import VcsApiRaw


class VcsApi(
    AuthorizeExternalDeployment,
    CreateProviderRepository,
    DeleteInstallation,
    DetectRuntimeSettings,
    GetInstallationById,
    GetRepository,
    ListInstallations,
    ListProviderRepositories,
    ListRepositoryBranches,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: VcsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = VcsApiRaw(api_client)
