# coding: utf-8

"""
    Appwrite

    Appwrite backend as a service cuts up to 70% of the time and costs required for building a modern application. We abstract and simplify common development tasks behind a REST APIs, to help you develop your app in a fast and secure way. For full API documentation and tutorials go to [https://appwrite.io/docs](https://appwrite.io/docs)

    The version of the OpenAPI document: 1.5.0
    Contact: team@appwrite.io
    Created by: https://appwrite.io/support
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from appwrite_console_python_sdk import schemas  # noqa: F401


class MigrationsCreateNHostMigrationRequest(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "database",
            "password",
            "resources",
            "subdomain",
            "adminSecret",
            "region",
            "username",
        }
        
        class properties:
        
            @staticmethod
            def resources() -> typing.Type['MigrationsCreateNHostMigrationRequestResources']:
                return MigrationsCreateNHostMigrationRequestResources
            subdomain = schemas.StrSchema
            region = schemas.StrSchema
            adminSecret = schemas.StrSchema
            database = schemas.StrSchema
            username = schemas.StrSchema
            password = schemas.StrSchema
            port = schemas.IntSchema
            __annotations__ = {
                "resources": resources,
                "subdomain": subdomain,
                "region": region,
                "adminSecret": adminSecret,
                "database": database,
                "username": username,
                "password": password,
                "port": port,
            }
    
    database: MetaOapg.properties.database
    password: MetaOapg.properties.password
    resources: 'MigrationsCreateNHostMigrationRequestResources'
    subdomain: MetaOapg.properties.subdomain
    adminSecret: MetaOapg.properties.adminSecret
    region: MetaOapg.properties.region
    username: MetaOapg.properties.username
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resources"]) -> 'MigrationsCreateNHostMigrationRequestResources': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["subdomain"]) -> MetaOapg.properties.subdomain: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["region"]) -> MetaOapg.properties.region: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["adminSecret"]) -> MetaOapg.properties.adminSecret: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["database"]) -> MetaOapg.properties.database: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["username"]) -> MetaOapg.properties.username: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["password"]) -> MetaOapg.properties.password: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["port"]) -> MetaOapg.properties.port: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["resources", "subdomain", "region", "adminSecret", "database", "username", "password", "port", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resources"]) -> 'MigrationsCreateNHostMigrationRequestResources': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["subdomain"]) -> MetaOapg.properties.subdomain: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["region"]) -> MetaOapg.properties.region: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["adminSecret"]) -> MetaOapg.properties.adminSecret: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["database"]) -> MetaOapg.properties.database: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["username"]) -> MetaOapg.properties.username: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["password"]) -> MetaOapg.properties.password: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["port"]) -> typing.Union[MetaOapg.properties.port, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["resources", "subdomain", "region", "adminSecret", "database", "username", "password", "port", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        database: typing.Union[MetaOapg.properties.database, str, ],
        password: typing.Union[MetaOapg.properties.password, str, ],
        resources: 'MigrationsCreateNHostMigrationRequestResources',
        subdomain: typing.Union[MetaOapg.properties.subdomain, str, ],
        adminSecret: typing.Union[MetaOapg.properties.adminSecret, str, ],
        region: typing.Union[MetaOapg.properties.region, str, ],
        username: typing.Union[MetaOapg.properties.username, str, ],
        port: typing.Union[MetaOapg.properties.port, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'MigrationsCreateNHostMigrationRequest':
        return super().__new__(
            cls,
            *args,
            database=database,
            password=password,
            resources=resources,
            subdomain=subdomain,
            adminSecret=adminSecret,
            region=region,
            username=username,
            port=port,
            _configuration=_configuration,
            **kwargs,
        )

from appwrite_console_python_sdk.model.migrations_create_n_host_migration_request_resources import MigrationsCreateNHostMigrationRequestResources
