from appwrite_console_python_sdk.paths.vcs_github_installations_installation_id_provider_repositories_provider_repository_id.get import ApiForget


class VcsGithubInstallationsInstallationIdProviderRepositoriesProviderRepositoryId(
    ApiForget,
):
    pass
