from appwrite_console_python_sdk.paths.vcs_github_installations_installation_id_provider_repositories_provider_repository_id_detection.post import ApiForpost


class VcsGithubInstallationsInstallationIdProviderRepositoriesProviderRepositoryIdDetection(
    ApiForpost,
):
    pass
